### PR TITLE
Add typescript support

### PR DESCRIPTION
**Pull request by doxiaodong**
https://github.com/eleme/element-react/issues/352

Please makes sure these boxes are checked before submitting your PR, thank you!

* [x] Make sure you are merging your commits to `master` branch.
* [x] Add some descriptions and refer relative issues for you PR.
* [x] Rebase your commits to make your pull request meaningful.
* [x] Make sure that your changes pass `npm test`, `npm run lint` and `npm run build`.

Changes in this pull request

- Add typings
- 除了 Tree, Carousel 以外，其他组件均只添加了 props type.
- Input 和 Datetimepicker 的测试写得不完整

顺便，为什么把 yarn.lock ignore 了

### CODE REVIEW

**Comment by e1emeb0t** [comment]
Can rebase your commits before we can merge your pull request?

**Comment by doxiaodong** [comment]
done

**Comment by e1emeb0t** [comment]
Umm... Not this way, you need create another pull request with the rebased commited, then you will see the new pull request only has one commit.

**Comment by doxiaodong** [comment]
soga

**Comment by doxiaodong** [comment]
close?

**Comment by e1emeb0t** [comment]
Sorry, I thought you need create another new pull request, my BAD😂

**Comment by e1emeb0t** [comment]
Sorry, I don't have any experience with yarn, so I googled `yarn.lock` and found this blog https://yarnpkg.com/blog/2016/11/24/lockfiles-for-all/, it seems that `yarn.lock` should be commited.

**Comment by doxiaodong** [comment]
It's useful to use yarn.lock to lock version. And travis config is easy. https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn

**Comment by e1emeb0t** [comment]
Appreciate, I'll commit this change.

**Pull request merged**
